# -*- coding: utf-8 -*-
"""Exp1&2 Data Mining

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_YNOzIhAR7gW95VXMjtJaAXjrN6DftsP
"""



"""**Experiment-1** : Central Tendency Measures: Mean(Avg), Median(Middle Value), Mode(Repetition)"""

import pandas as pd

Data=pd.read_excel("Exp1 Data Mining.xlsx")

Data

A=Data['A']

A

B=Data['B']

B

X_Mean=A.mean()

X_Mean

Y_Mean=B.mean()

Y_Mean

A.median()

B.median()

print(f"X_Mean:{X_Mean}")

print(f"X_Median:{A.median()}")

A_mod,B_mod=A.mode().iloc[0],B.mode().iloc[0]

A_mod

B_mod

"""**Experiment-2**: Dispersion Estimation Measures  : Range. Standard Deviation, Variance, IQR
1)Range=max-min


"""

Range=A.max()-B.min()

Range

Q3=A.quantile(0.75)

Q1=A.quantile(0.25)

IQR=Q3-Q1

IQR

from scipy import stats

iqr_A=stats.iqr(A)

iqr_A

iqr_B=stats.iqr(B)

iqr_B

A_std=A.std()

A_std

B_std=B.std()

B_std

"""Less VARIANCE= More Stable , and vice versa"""

A_var=A.var()

A_var

B_var=B.var()

B_var

"""Why we use Square instead of Mode in Variance"""

Data=[0,2,3,4,5,6,7,8,9]

Data

X=pd.Series(Data)

X

X.mean()

X.median()

